### ISSUE TITLE
XSETBV unhandled?

### ISSUE THREAD

**Issue by BomboBombone** [MellowNight/AetherVisor#9]
title says it all, I cannot find a reference to any xsetbv handling code, which could easily crash a system

![image](https://user-images.githubusercontent.com/88135556/230739625-2db0ac4e-acae-4bf4-b26d-b9b99a40cfa4.png)

**Comment by jonomango** [comment]
The hypervisor doesn't VM-exit on XSETBV (guest_vmcb.control_area.intercept_vec4 isn't configured to) so it shouldn't be an issue. The CPU will execute the instruction as normal using the guest state, from my understanding. I'm not too familiar with AMD-V so feel free to correct me if I'm wrong.

**Comment by BomboBombone** [comment]
Makes sense, xsetbv can be handled by the CPU if configured to.
